# M68K isn't directly supported, so just use C.
language: c

script:
  - cd "${TRAVIS_BUILD_DIR}/Build Scripts" && python build.py -verbose 3K
  - cd "${TRAVIS_BUILD_DIR}/Build Scripts" && python build.py -verbose S3
  - cd "${TRAVIS_BUILD_DIR}/Build Scripts" && python build.py -verbose -accurate SK
  - cd "${TRAVIS_BUILD_DIR}/Build Scripts" && python build.py -verbose verifyS3
  - cd "${TRAVIS_BUILD_DIR}/Build Scripts" && python build.py -verbose verifySK

notifications:
  irc: "ircs://irc.badnik.zone:6697/#repo"
