# M68K isn't directly supported, so just use C.
language: c

script:
  - cd "${TRAVIS_BUILD_DIR}/Build Scripts" && python build.py -verbose 3K
  - cd "${TRAVIS_BUILD_DIR}/Build Scripts" && python build.py -verbose SK
  - cd "${TRAVIS_BUILD_DIR}/Build Scripts" && python build.py -verbose verify

notifications:
  irc: "ircs://irc.badnik.zone:6697/#repo"
